"""Tests for auto-registered component edges from ``.vue`` templates.

``unplugin-vue-components`` and Nuxt register components globally, so a template
tag has no import statement for the script pass to edge. :func:`extract_vue`
resolves those tags through the generated ``components.d.ts`` registry and emits
a ``uses`` edge per rendered component.
"""
from __future__ import annotations

from pathlib import Path

from graphify.extract import (
    _VUE_COMPONENTS_DTS_CACHE,
    _kebab,
    _load_vue_components_dts,
    extract_vue,
)


def _write(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


COMPONENTS_DTS = """/* generated by unplugin-vue-components */
export {}
declare module 'vue' {
  export interface GlobalComponents {
    ChildDialog: typeof import('./src/components/ChildDialog.vue')['default']
    SearchField: typeof import('./src/components/SearchField.vue')['default']
    SelfRef: typeof import('./src/components/SelfRef.vue')['default']
  }
}
"""


def _project(tmp_path: Path) -> Path:
    _write(tmp_path / "components.d.ts", COMPONENTS_DTS)
    _write(tmp_path / "src/components/ChildDialog.vue", "<template><b/></template>\n")
    _write(tmp_path / "src/components/SearchField.vue", "<template><i/></template>\n")
    return tmp_path


def _uses(result: dict) -> set[str]:
    return {
        Path(e["target_file"]).name
        for e in result.get("edges", [])
        if e.get("relation") == "uses" and e.get("target_file")
    }


def setup_function() -> None:
    _VUE_COMPONENTS_DTS_CACHE.clear()


def test_kebab_spelling():
    assert _kebab("ConfirmDeleteDialog") == "confirm-delete-dialog"
    assert _kebab("VBtn") == "v-btn"


def test_registry_is_read_from_a_gitignored_dts(tmp_path: Path):
    _project(tmp_path)
    registry = _load_vue_components_dts(tmp_path / "src/views")
    # Specifier is rewritten relative to the SFC's own directory, not the root.
    assert registry["ChildDialog"] == "../components/ChildDialog.vue"
    assert registry["child-dialog"] == "../components/ChildDialog.vue"


def test_template_only_component_gets_a_uses_edge(tmp_path: Path):
    _project(tmp_path)
    sfc = _write(
        tmp_path / "src/views/Page.vue",
        "<template>\n"
        "  <div>\n"
        "    <ChildDialog :open=\"open\" />\n"
        "    <search-field />\n"
        "  </div>\n"
        "</template>\n"
        "<script setup lang=\"ts\">\n"
        "const open = ref(false)\n"
        "</script>\n",
    )
    assert _uses(extract_vue(sfc)) == {"ChildDialog.vue", "SearchField.vue"}


def test_explicit_import_is_not_edged_twice(tmp_path: Path):
    _project(tmp_path)
    sfc = _write(
        tmp_path / "src/views/Explicit.vue",
        "<template><ChildDialog /></template>\n"
        "<script setup lang=\"ts\">\n"
        "import ChildDialog from '../components/ChildDialog.vue'\n"
        "</script>\n",
    )
    result = extract_vue(sfc)
    assert _uses(result) == set()
    targets = [
        e for e in result["edges"]
        if str(e.get("target_file") or "").endswith("ChildDialog.vue")
    ]
    assert len(targets) == 1


def test_recursive_component_does_not_edge_itself(tmp_path: Path):
    _project(tmp_path)
    sfc = _write(
        tmp_path / "src/components/SelfRef.vue",
        "<template><SelfRef v-if=\"deep\" /></template>\n"
        "<script setup lang=\"ts\">\n"
        "const deep = false\n"
        "</script>\n",
    )
    assert _uses(extract_vue(sfc)) == set()


def test_html_and_unregistered_tags_are_ignored(tmp_path: Path):
    _project(tmp_path)
    sfc = _write(
        tmp_path / "src/views/Plain.vue",
        "<template>\n"
        "  <div><span/><UnknownThing /><template #slot><i/></template></div>\n"
        "</template>\n",
    )
    assert _uses(extract_vue(sfc)) == set()


def test_no_components_dts_means_no_new_edges(tmp_path: Path):
    sfc = _write(
        tmp_path / "src/views/Bare.vue",
        "<template><ChildDialog /></template>\n",
    )
    assert _uses(extract_vue(sfc)) == set()


def test_walk_stops_at_the_package_boundary(tmp_path: Path):
    """A components.d.ts above this project's package.json is a different app."""
    _write(tmp_path / "components.d.ts", COMPONENTS_DTS)
    _write(tmp_path / "src/components/ChildDialog.vue", "<template><b/></template>\n")
    inner = tmp_path / "packages" / "other"
    _write(inner / "package.json", '{"name": "other"}')
    sfc = _write(
        inner / "src/Page.vue",
        "<template><ChildDialog /></template>\n",
    )
    assert _load_vue_components_dts(sfc.parent) == {}
    assert _uses(extract_vue(sfc)) == set()
