"""Tests for solution-style ``tsconfig.json`` (``files: []`` + ``references``).

The root config generated by ``create-vue``/``create-vite`` holds no
``compilerOptions``; the real ``paths`` live in the referenced projects, and tsc
assigns each source file to the project whose ``include``/``files`` cover it.
Reading only the root yielded an empty alias map, so every ``@/…`` import in
such a repo resolved to a ghost node instead of the real file.
"""
from __future__ import annotations

import json
from pathlib import Path

from graphify.extractors.resolution import (
    _TSCONFIG_ALIAS_CACHE,
    _TSCONFIG_BASEURL_CACHE,
    _TSCONFIG_REFERENCE_ALIAS_CACHE,
    _TSCONFIG_REFERENCE_BASEURL_CACHE,
    _load_tsconfig_aliases,
    _load_tsconfig_base_url,
)


def setup_function() -> None:
    for cache in (
        _TSCONFIG_ALIAS_CACHE,
        _TSCONFIG_BASEURL_CACHE,
        _TSCONFIG_REFERENCE_ALIAS_CACHE,
        _TSCONFIG_REFERENCE_BASEURL_CACHE,
    ):
        cache.clear()


def _write(path: Path, data: dict) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data), encoding="utf-8")
    return path


def _solution(tmp_path: Path, *refs: str) -> None:
    _write(tmp_path / "tsconfig.json", {
        "files": [],
        "references": [{"path": f"./{r}"} for r in refs],
    })


def test_alias_comes_from_the_referenced_project_that_covers_the_file(tmp_path: Path):
    _solution(tmp_path, "tsconfig.node.json", "tsconfig.app.json")
    _write(tmp_path / "tsconfig.app.json", {
        "include": ["src/**/*"],
        "compilerOptions": {"paths": {"@/*": ["./src/*"]}},
    })
    _write(tmp_path / "tsconfig.node.json", {"include": ["vite.config.*"]})
    (tmp_path / "src/components").mkdir(parents=True)

    aliases = _load_tsconfig_aliases(tmp_path / "src/components")
    assert aliases == {"@/*": [str(tmp_path / "src" / "*")]}


def test_most_specific_covering_project_wins(tmp_path: Path):
    _solution(tmp_path, "tsconfig.app.json", "tsconfig.admin.json")
    _write(tmp_path / "tsconfig.app.json", {
        "include": ["src/**/*"],
        "compilerOptions": {"paths": {"@/*": ["./src/*"]}},
    })
    _write(tmp_path / "tsconfig.admin.json", {
        "include": ["src/admin/**/*"],
        "compilerOptions": {"paths": {"@/*": ["./src/admin/*"]}},
    })
    (tmp_path / "src/admin/views").mkdir(parents=True)

    aliases = _load_tsconfig_aliases(tmp_path / "src/admin/views")
    assert aliases == {"@/*": [str(tmp_path / "src" / "admin" / "*")]}


def test_uncovered_directory_falls_back_to_every_referenced_project(tmp_path: Path):
    _solution(tmp_path, "tsconfig.app.json")
    _write(tmp_path / "tsconfig.app.json", {
        "include": ["src/**/*"],
        "compilerOptions": {"paths": {"@/*": ["./src/*"]}},
    })
    (tmp_path / "scripts").mkdir()

    # Nothing covers scripts/, but a single shared alias is the common layout.
    assert _load_tsconfig_aliases(tmp_path / "scripts") == {
        "@/*": [str(tmp_path / "src" / "*")]
    }


def test_root_with_its_own_paths_ignores_references(tmp_path: Path):
    _write(tmp_path / "tsconfig.json", {
        "references": [{"path": "./tsconfig.app.json"}],
        "compilerOptions": {"paths": {"@/*": ["./app/*"]}},
    })
    _write(tmp_path / "tsconfig.app.json", {
        "include": ["src/**/*"],
        "compilerOptions": {"paths": {"@/*": ["./src/*"]}},
    })
    (tmp_path / "src").mkdir()

    assert _load_tsconfig_aliases(tmp_path / "src") == {
        "@/*": [str(tmp_path / "app" / "*")]
    }


def test_base_url_is_taken_from_the_referenced_project(tmp_path: Path):
    _solution(tmp_path, "tsconfig.app.json")
    _write(tmp_path / "tsconfig.app.json", {
        "include": ["src/**/*"],
        "compilerOptions": {"baseUrl": "./src"},
    })
    (tmp_path / "src").mkdir()

    assert _load_tsconfig_base_url(tmp_path / "src") == tmp_path / "src"


def test_missing_or_malformed_reference_is_survivable(tmp_path: Path):
    _write(tmp_path / "tsconfig.json", {
        "files": [],
        "references": [{"path": "./nope.json"}, "not-an-object", {}],
    })
    (tmp_path / "src").mkdir()

    assert _load_tsconfig_aliases(tmp_path / "src") == {}
    assert _load_tsconfig_base_url(tmp_path / "src") is None


def test_plain_config_without_references_is_unchanged(tmp_path: Path):
    _write(tmp_path / "tsconfig.json", {
        "compilerOptions": {"paths": {"@/*": ["./src/*"]}},
    })
    (tmp_path / "src").mkdir()

    assert _load_tsconfig_aliases(tmp_path / "src") == {
        "@/*": [str(tmp_path / "src" / "*")]
    }
